<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="winfsp.net" Version="2.2.26112" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AxCrypt.Core\AxCrypt.Core.csproj" />
  </ItemGroup>

</Project>
